---
deployment:
  tasks:
    - export DEPLOYPATH=/home/aywsolution/public_html/somosperu.aywsolution.com
    - /bin/rsync -a --exclude 'index.php' /home/aywsolution/repositories/somosperu-wb/public/ $DEPLOYPATH
    - export DEPLOYPATH=/home/aywsolution/web_somosperu/
    - /bin/rsync -a --exclude 'public/' * $DEPLOYPATH